apiVersion: apps/v1
kind: Deployment
metadata:
  name: silvester-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: silvester-web
  template:
    metadata:
      labels:
        app: silvester-web
    spec:
      containers:
        - name: silvester-container
          image: silvester-website
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80