name: CI/CD Pipeline - Silvester Web App

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Image
        run: |
          docker build -t silvesteranto/silvester-website:latest .
          docker push silvesteranto/silvester-website:latest

      - name: Start Minikube
        uses: medyagh/setup-minikube@master
        with:
          driver: docker

      - name: Verify Cluster
        run: kubectl get pods -A

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Initialize Terraform
        working-directory: ./iac
        run: terraform init

      - name: Apply Terraform
        working-directory: ./iac
        env:
          TF_VAR_docker_image: silvesteranto/silvester-website:latest
        run: terraform apply -auto-approve -lock=false
